# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name : NetCore-HelloAzure-CI
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - HelloAzureCI/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/HelloAzure*.csproj'
  displayName: 'Restore Nuget Packages'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/HelloAzure*.csproj'
    arguments: '--no-restore'
  displayName: 'Build projects'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Test.csproj'
    arguments: '--no-restore --no-build'
  displayName: 'Run Tests'  
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/HelloAzureCI.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
    modifyOutputPath: false
  displayName: 'Publish HelloAzureCI'  
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
